package cn.xmo.dao.cargo;

import cn.xmo.domain.cargo.Export;
import cn.xmo.domain.cargo.ExportExample;

import java.util.List;

public interface ExportDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_export
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_export
     *
     * @mbg.generated
     */
    int insert(Export record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_export
     *
     * @mbg.generated
     */
    int insertSelective(Export record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_export
     *
     * @mbg.generated
     */
    List<Export> selectByExample(ExportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_export
     *
     * @mbg.generated
     */
    Export selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_export
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Export record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_export
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Export record);
}