package cn.xmo.dao.cargo;

import cn.xmo.domain.cargo.ExportProduct;
import cn.xmo.domain.cargo.ExportProductExample;

import java.util.List;

public interface ExportProductDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_export_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_export_product
     *
     * @mbg.generated
     */
    int insert(ExportProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_export_product
     *
     * @mbg.generated
     */
    int insertSelective(ExportProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_export_product
     *
     * @mbg.generated
     */
    List<ExportProduct> selectByExample(ExportProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_export_product
     *
     * @mbg.generated
     */
    ExportProduct selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_export_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ExportProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_export_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ExportProduct record);
}