package cn.xmo.dao.cargo;

import cn.xmo.domain.cargo.ExtEproduct;
import cn.xmo.domain.cargo.ExtEproductExample;

import java.util.List;

public interface ExtEproductDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_ext_eproduct
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_ext_eproduct
     *
     * @mbg.generated
     */
    int insert(ExtEproduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_ext_eproduct
     *
     * @mbg.generated
     */
    int insertSelective(ExtEproduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_ext_eproduct
     *
     * @mbg.generated
     */
    List<ExtEproduct> selectByExampleWithBLOBs(ExtEproductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_ext_eproduct
     *
     * @mbg.generated
     */
    List<ExtEproduct> selectByExample(ExtEproductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_ext_eproduct
     *
     * @mbg.generated
     */
    ExtEproduct selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_ext_eproduct
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ExtEproduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_ext_eproduct
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ExtEproduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_ext_eproduct
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ExtEproduct record);
}