package cn.xmo.dao.system;

import cn.xmo.domain.system.Module;
import cn.xmo.domain.system.ModuleExample;

import java.util.List;

public interface ModuleDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_module
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String moduleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_module
     *
     * @mbg.generated
     */
    int insert(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_module
     *
     * @mbg.generated
     */
    int insertSelective(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_module
     *
     * @mbg.generated
     */
    List<Module> selectByExample(ModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_module
     *
     * @mbg.generated
     */
    Module selectByPrimaryKey(String moduleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_module
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_module
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Module record);

    List<Module> findByRoleId(String roleId);

    List<Module> findByBelong(int i);

    List<Module> findByUserId(String userId);
}